### ISSUE TITLE
请问现在官方翻译进度怎么样？

### ISSUE THREAD

**Issue by qq2211042368** [jitingcn/TS3-Translation_zh-CN#11]
最近看到TS5中文界面是否是官方的

**Comment by jitingcn** [comment]
首先这个项目是非官方的，我们只是普通的 teamspeak 使用者，出于爱好制作的语言包。
我们并不了解官方的进度。另外我刚刚更新了最新的 TS5 版本，经常过没有语言的设置，请问你是在哪里看到的中文界面？

**Comment by qq2211042368** [comment]
十分抱歉，刚刚又重新看了一下 “我所看到的TS5中文界面”，其实是TS3的一个主题，和TS5默认主题很相似，我看错了。
非常感谢，您的回复。
