### ISSUE TITLE
翻译改进提议

### ISSUE THREAD

**Issue by GarliCcccc** [jitingcn/TS3-Translation_zh-CN#5]
### Options下

- 选项卡`音频捕获` 应改为 `录音`或者`录制`，抑或是类似macOS的命名风格`麦克风`
- 单选项`语音激活检测`应改为更加直观的，例如`语音自动激活（设置激活门槛）`
- 复选项`减小回音`应改为更加书面化的`回声抑制`，以及`消除回音`改为`回声消除`。
- 复选项`延迟释放按键通话：`应改为`按键通话释放后延迟：`

**Comment by EdisonJwa** [comment]
我感觉这个提议是不错的，可以考虑一下
回音这个我打算按你说的这个改了
其他的可能要讨论一下

**Comment by jitingcn** [comment]
已更新，第一个提议还需要再讨论一下......
目前的音频捕获参考了obs的译法
