### ISSUE TITLE
5.0测试中……

### ISSUE THREAD

**Issue by huangsijun17** [jitingcn/TS3-Translation_zh-CN#8]
要不我发个邮件问一下官方是否会发布官方中文版本？再去要个语言文件来？

**Comment by jitingcn** [comment]
TS5 肯定支持简体中文，在 locales 文件夹下存在 zh-CN.pak，但应该还未实装，软件内没有语言设置选项，替换文件也没有效果。

**Comment by PRAJNAPLAYER** [comment]
啥时候会发布5.0呢

**Comment by PRAJNAPLAYER** [comment]
又过去了2个月，5.0还在测试
